project:
  type: website
  output-dir: docs

website:
  title: "Trabalho final GC e visualizadores"
  navbar:
    left:
      - href: index.qmd
        text: Inicial
        icon: Houses
      - href: about.qmd
        text: Sobre
      - href: dash_cb.html
        text: Painel

format:
  html:
    theme: lux
    css: styles.css
    toc: true



